bin/screenshot: Update file output format; Added bin/syncthing-start

diff --git a/bin/screenshot b/bin/screenshot
--- a/bin/screenshot
+++ b/bin/screenshot
@@ -1,9 +1,14 @@
 #!/bin/bash
 
+if ! which gnome-screenshot &> /dev/null; then
+  (>&2 echo -e "$0 ERROR\n  \`gnome-screenshot' is not available.\n  Exiting.")
+  exit 1
+fi
+
 root_path="$HOME/Pictures/Screenshots"
 
 if [ ! -d "$root_path" ]; then
-	mkdir -p $root_path
+  mkdir -p $root_path
 fi
 
 year="$( date +%Y )"
@@ -13,19 +18,22 @@ day="$( date +%d )"
 path="${root_path}/${year}/${month}/${day}"
 
 if [ ! -d "$path" ]; then
-	mkdir -p $path
+  mkdir -p $path
 fi
 
 extra=""
 if   [ "$1" == "-a" ]; then
-	extra="_area"
+  extra="_area"
 elif [ "$1" == "-w" ]; then
-	extra="_window"
+  extra="_window"
 fi
 
-filename="${path}/$( date +%H:%M:%S )${extra}.png"
+filename="${path}/$( date "+%H%M%S" )${extra}.png"
 gnome-screenshot -f $filename $@
 
-# Make latest soft link
+# Make soft link to image
 rm -f ${root_path}/latest
 ln -s $filename ${root_path}/latest
+# Make soft link to image's directory
+rm -f ${root_path}/latest-date
+ln -s $path ${root_path}/latest-date
