Update run-stow script, use util.sh, optionally list specific packages to stow

diff --git a/run-stow b/run-stow
--- a/run-stow
+++ b/run-stow
@@ -17,12 +17,13 @@
 
 set -eo pipefail
 
-ROOT="$( \
-    cd "$( \
-        dirname "$( realpath "$0" )" \
-    )" || exit 1; \
-    pwd \
-)"
+# shellcheck source=./util.sh disable=SC2155
+function _dl_util_sh {
+    local UTIL_VERSION="v2.2.6"
+    local dir="$( dirname "$1" )/bin/bin"
+    [ -f "${dir}/util.sh" ] || bash "${dir}/download-util.sh" "$UTIL_VERSION" || exit 1
+    source "${dir}/util.sh"
+}; _dl_util_sh "$0"
 
 DOTS_BACKUP_SUFFIX=".pre-stow"
 STOW_TARGET="$HOME"
@@ -33,9 +34,6 @@ IGNORED_PKGS=( \
     "LICENSE"            \
 )
 STOW_STDERR_FILE="${ROOT}/.stow-err"
-
-# https://stackoverflow.com/a/17841619/10927893
-function join_by { local IFS="$1"; shift; echo "$*"; }
 
 function main {
     run_stow "$@"
@@ -54,6 +52,25 @@ function run_stow {
     mapfile -t files < <( \
         ls -1d -- * | grep -v '^\('"${invert_pkgs_regex}"'\)$' )
 
+    stow_files "${files[@]}"
+}
+
+function stow_files {
+    local files=("$@")
+
+    msg "Packages to stow:"
+    printf "  %s\n" "${files[@]}"
+
+    if ! prompt_question "Stow these packages?" "n"; then
+        prompt_question "Select packages to stow?" "n" || quit
+        select_packages_to_stow files
+        stow_files "${files[@]}"
+        return
+    fi
+
+    msg "Stowing packages:"
+    printf "  %s\n" "${files[@]}"
+
     stow \
         --target "$STOW_TARGET" \
         --ignore '^(_.*)|(.*\.log)|((cmd|run)_(stdout|stderr))$' \
@@ -67,55 +84,68 @@ function run_stow {
 }
 
 function maybe_backup_conflicting_dots {
-    local input
     local conflicting_dots
     local cmd
 
     ( 1>&2 cat "$STOW_STDERR_FILE" )
 
-    echo -en "\
-\`stow\` didn't exit successfully.
-Possibly conflicting dotfiles exist.
-Automatically rename all conflicting dotfiles with
-the suffix \`${DOTS_BACKUP_SUFFIX}\`? [y|N] "
+    msg "\`stow\` didn't exit successfully. Possibly conflicting dotfiles exist."
+    prompt_question "Automatically rename all conflicting dotfiles with the suffix \`${DOTS_BACKUP_SUFFIX}\`?" "n" \
+        || quit
+    msg "Renaming conflicting dotfiles with suffix \`${DOTS_BACKUP_SUFFIX}\`..."
 
-    read -rn1 input
-    echo
-    if [ "$input" = "y" ] || [ "$input" = "Y" ]; then
-        echo "Renaming conflicting dotfiles with suffix \`${DOTS_BACKUP_SUFFIX}\`..."
+    mapfile -t conflicting_dots < <( \
+        grep -oE \
+        'existing target is neither a link nor a directory: .+$' \
+        "$STOW_STDERR_FILE" \
+        | rev \
+        | cut -d" " -f1 \
+        | rev \
+        | sed 's,\(^.\+$\),'"${STOW_TARGET}"'/\1,'
+    )
 
-        mapfile -t conflicting_dots < <( \
-            grep -oE \
-            'existing target is neither a link nor a directory: .+$' \
-            "$STOW_STDERR_FILE" \
-            | rev \
-            | cut -d" " -f1 \
-            | rev \
-            | sed 's,\(^.\+$\),'"${STOW_TARGET}"'/\1,'
-        )
+    [ ${#conflicting_dots[@]} -gt 0 ] \
+        || {
+            warn "No conflicing dots? Exiting"
+            exit 1
+        }
 
-        [ ${#conflicting_dots[@]} -gt 0 ] \
-            || {
-                echo "No conflicing dots? Exiting"
-                exit 1
-            }
+    for dotfile in "${conflicting_dots[@]}"; do
+        cmd=( mv "$dotfile" "${dotfile}${DOTS_BACKUP_SUFFIX}" )
+        try_run "${cmd[@]}"
+    done
 
-        for dotfile in "${conflicting_dots[@]}"; do
-            cmd=( mv "$dotfile" "${dotfile}${DOTS_BACKUP_SUFFIX}" )
-            echo "${cmd[@]}"
-            "${cmd[@]}"
-        done
+    msg "Moved all files, running \`stow\` again..."
+    run_stow "$@"
+}
 
-        echo "Moved all files, running \`stow\` again..."
-        run_stow "$@"
-    else
-        echo "Exiting"
-        exit 1
-    fi
+function select_packages_to_stow {
+    local -n return_files="$1"
+
+    msg "Enter space-separated list of package names to stow:"
+
+    local selected_files=()
+    read -ra selected_files
+
+    return_files=()
+    for file in "${selected_files[@]}"; do
+        [ -d "$file" ] || {
+            warn "Package \`${file}\` not found, skipping"
+            continue
+        }
+        return_files+=( "$file" )
+    done
+}
+
+function quit {
+    echo "Exiting"
+    exit 1
 }
 
 function cleanup {
+    code=$?
     [ -f "$STOW_STDERR_FILE" ] && rm "$STOW_STDERR_FILE"
+    return $code
 }
 
 trap cleanup EXIT QUIT TERM INT
