bin/tmux-fa: Update script: check docker, project paths

diff --git a/bin/bin/tmux-fa b/bin/bin/tmux-fa
--- a/bin/bin/tmux-fa
+++ b/bin/bin/tmux-fa
@@ -12,16 +12,29 @@ function _dl_util_sh {
 
 set -e
 
-PROJ_FE="${HOME}/Projects/ANX/freelancer-marktplatz"
-PROJ_ADMIN="${HOME}/Projects/ANX/freelancer-marktplatz-admin"
-TMUX_SESS="fa"
-TMUX_KEYBIND_QUIT="-n C-Q"
+[ -z "$PROJ_FE" ] && PROJ_FE="$PWD"
+[ -z "$PROJ_ADMIN" ] && PROJ_ADMIN=$( realpath "../freelancer-marktplatz-admin" )
+[ -z "$TMUX_SESS" ] && TMUX_SESS="fa"
+[ -z "$TMUX_KEYBIND_QUIT" ] && TMUX_KEYBIND_QUIT="-n C-Q"
+
+DOCKER_COMPOSE="docker compose"
 
 check "tmux"
 check_dir "$PROJ_FE"
-check_dir "$PROJ_ADMIN"
 
 function main {
+
+    check_proj "$PROJ_FE"
+
+    if has_proj_admin; then
+        check_proj "$PROJ_ADMIN"
+    else
+        warn "Project not found, skipping: ${PROJ_ADMIN}"
+    fi
+
+    check_docker
+    check_docker_compose
+
     if is_session_running; then
         attach_session
         exit $?
@@ -39,23 +52,95 @@ function attach_session {
 }
 
 function create_session {
-    try_run tmux new-session \
-        -s "$TMUX_SESS" \
-        -c "$PROJ_FE" -e "AUTO_CDPATH=0" \
-        -n "docker" docker compose up \; \
-        new-window -c "$PROJ_ADMIN" -e "AUTO_CDPATH=0" \
-            -n "admin" docker compose up \; \
-        new-window -c "${PROJ_FE}/apps/website" -e "AUTO_CDPATH=0" \
-            -n "dev" yarn run dev \; \
-        new-window -c "${PROJ_FE}/packages/cron" -e "AUTO_CDPATH=0" \
-            -n "cron" yarn run dev \; \
-        select-window -t "dev" \; \
-        bind-key $TMUX_KEYBIND_QUIT \
-            send-keys -t "docker" "C-c" \\\; \
-            send-keys -t "admin"  "C-c" \\\; \
-            send-keys -t "dev"    "C-c" \\\; \
-            send-keys -t "cron"   "C-c" \
-        "$@"
+    local tmux_cmd='
+        new-session
+            -s '"$TMUX_SESS"'
+            -c '"$PROJ_FE"' -e AUTO_CDPATH=0
+            -n app docker compose up ;
+            '"$( has_proj_admin && echo -n "
+                new-window -c "$PROJ_ADMIN" -e AUTO_CDPATH=0
+                    -n admin docker compose up ;
+            " )"'
+            new-window -c '"${PROJ_FE}/apps/website"' -e AUTO_CDPATH=0
+                -n dev yarn run dev ;
+            new-window -c '"${PROJ_FE}/packages/cron"' -e AUTO_CDPATH=0
+                -n cron yarn run dev ;
+            select-window -t dev ;
+            bind-key '"$TMUX_KEYBIND_QUIT"'
+                send-keys -t app    C-c \;
+                '"$( has_proj_admin && echo -n "
+                    send-keys -t admin C-c \;
+                " )"'
+                send-keys -t dev    C-c \;
+                send-keys -t cron   C-c
+    '
+
+    try_run tmux $tmux_cmd "$@"
+}
+
+function has_proj_admin {
+    [ -d "$PROJ_ADMIN" ]
+}
+
+function check_proj {
+    local proj="$1"
+    [ -d "$proj" ] || err "Project not found: $proj"
+    check_proj_dir "$proj" ".git"
+    check_proj_file "$proj" "package.json"
+}
+
+function check_proj_file {
+    check_proj_file_or_dir "$1" "$2" file
+}
+
+function check_proj_dir {
+    check_proj_file_or_dir "$1" "$2" dir
+}
+
+function check_proj_file_or_dir {
+    local proj="$1"
+    local file="$2"
+    local type="$3"
+
+    local cmd=
+    if [ "$type" = "file" ]; then
+        cmd="-f"
+    elif [ "$type" = "dir" ]; then
+        cmd="-d"
+    else
+        err "[check_proj_file_or_dir] Invalid type: $type"
+    fi
+
+    [ "$cmd" "${proj}/${file}" ] || err "Project ${type} not found: $(clr white black bold)${proj}/${file}$(clrrs)"
+}
+
+function check_docker {
+    check "docker"
+
+    if docker info &>/dev/null; then
+        return 0
+    fi
+
+    warn "Docker not running. Starting docker daemon."
+
+    if is_available "systemctl"; then
+        systemctl is-active docker &>/dev/null || \
+            try_run sudo systemctl start docker
+    fi
+}
+
+function check_docker_compose {
+    if docker compose version &>/dev/null; then
+        DOCKER_COMPOSE="docker compose"
+        return 0
+    fi
+
+    if is_available "docker-compose"; then
+        DOCKER_COMPOSE="docker-compose"
+        return 0
+    fi
+
+    err "$(clr white black bold)docker-compose$(clrrs) is not available."
 }
 
 main "$@"
